// GENERATED by tools/lfm2_vl_tiling_oracle.py -- DO NOT EDIT BY HAND.
//
// Golden vectors for LFM2.5-VL multi-tile NaFlex, produced by running
// transformers' own (verbatim-extracted) tiling + token-markup functions
// against the shipped processor_config.json of LiquidAI/LFM2.5-VL-3B.
//
// Regenerate with:  python tools/lfm2_vl_tiling_oracle.py --emit-header \
//                       > tests/lfm2_tiling_golden.h

#pragma once

#include <stdint.h>

namespace lfm2_tiling_golden {

struct label { int row, col; };

struct layout_case {
    const char * name;
    int width, height;
    int split;                 // 1 = image is tiled
    int grid_w, grid_h;        // tile grid, geometric
    int rows, cols;            // what the processor LABELS them (see the swap)
    int n_tiles;               // grid_w * grid_h
    int n_images;              // tiles + thumbnail
    int has_thumb;
    int target_w, target_h;    // whole-image resize before cutting into tiles
    int resized_w, resized_h;  // smart_resize output (= thumbnail size when split)
    int tile_tokens;           // image tokens per 512x512 tile
    int thumb_tokens;          // image tokens for the smart_resize'd image
    int total_tokens;          // total <image> tokens in the prompt
    int n_labels;
    const label * labels;
};

static const label kLabels0[1] = { {0, 0} };  // unused
static const label kLabels1[1] = { {0, 0} };  // unused
static const label kLabels2[1] = { {0, 0} };  // unused
static const label kLabels3[1] = { {0, 0} };  // unused
static const label kLabels4[] = { {1, 1}, {1, 2}, {1, 3}, {2, 1}, {2, 2}, {2, 3} };
static const label kLabels5[] = { {1, 1}, {1, 2}, {1, 3}, {2, 1}, {2, 2}, {2, 3} };
static const label kLabels6[] = { {1, 1}, {1, 2}, {1, 3}, {2, 1}, {2, 2}, {2, 3}, {3, 1}, {3, 2}, {3, 3} };
static const label kLabels7[] = { {1, 1}, {2, 1}, {3, 1}, {4, 1} };
static const label kLabels8[1] = { {0, 0} };  // unused
static const label kLabels9[1] = { {0, 0} };  // unused
static const label kLabels10[1] = { {0, 0} };  // unused
static const label kLabels11[1] = { {0, 0} };  // unused
static const label kLabels12[1] = { {0, 0} };  // unused
static const label kLabels13[1] = { {0, 0} };  // unused
static const label kLabels14[1] = { {0, 0} };  // unused
static const label kLabels15[] = { {1, 1}, {1, 2}, {2, 1}, {2, 2}, {3, 1}, {3, 2} };
static const label kLabels16[] = { {1, 1}, {1, 2}, {1, 3}, {2, 1}, {2, 2}, {2, 3} };
static const label kLabels17[] = { {1, 1}, {2, 1}, {3, 1}, {4, 1}, {5, 1}, {6, 1}, {7, 1}, {8, 1}, {9, 1}, {10, 1} };
static const label kLabels18[] = { {1, 1}, {1, 2}, {1, 3}, {2, 1}, {2, 2}, {2, 3} };
static const label kLabels19[] = { {1, 1}, {1, 2}, {2, 1}, {2, 2} };

static const layout_case kCases[] = {
    { "the fixture (does not split -- regression canary)", 500, 650, 0, 1, 1, 1, 1, 1, 1, 0, 448, 576, 448, 576, 256, 252, 252, 0, kLabels0 },
    { "small thumbnail (upscaled into the token band)", 150, 200, 0, 1, 1, 1, 1, 1, 1, 0, 224, 320, 224, 320, 256, 70, 70, 0, kLabels1 },
    { "tall strip", 300, 1000, 0, 1, 1, 1, 1, 1, 1, 0, 256, 928, 256, 928, 256, 232, 232, 0, kLabels2 },
    { "wide banner", 1000, 300, 0, 1, 1, 1, 1, 1, 1, 0, 928, 256, 928, 256, 256, 232, 232, 0, kLabels3 },
    { "A4 scan @ 300 dpi", 3000, 4000, 1, 2, 3, 2, 3, 6, 7, 1, 1024, 1536, 416, 576, 256, 234, 1770, 6, kLabels4 },
    { "US letter @ 200 dpi", 1700, 2200, 1, 2, 3, 2, 3, 6, 7, 1, 1024, 1536, 448, 576, 256, 252, 1788, 6, kLabels5 },
    { "square", 2048, 2048, 1, 3, 3, 3, 3, 9, 10, 1, 1536, 1536, 512, 512, 256, 256, 2560, 9, kLabels6 },
    { "panorama", 4000, 1000, 1, 4, 1, 4, 1, 4, 5, 1, 2048, 512, 1024, 256, 256, 256, 1280, 4, kLabels7 },
    { "banker's rounding: 80/32 = 2.5 -> Python 64, C++ std::round 96", 80, 80, 0, 1, 1, 1, 1, 1, 1, 0, 256, 256, 256, 256, 256, 64, 64, 0, kLabels8 },
    { "banker's rounding on one axis only", 1200, 80, 0, 1, 1, 1, 1, 1, 1, 0, 1216, 64, 1216, 64, 256, 76, 76, 0, kLabels9 },
    { "banker's: no split / 252 tok; std::round: 1x10 split / 2812 tok", 144, 4000, 0, 1, 1, 1, 1, 1, 1, 0, 96, 2688, 96, 2688, 256, 252, 252, 0, kLabels10 },
    { "banker's: 256x256 / 64 tok; std::round: 288x288 / 81 tok", 272, 272, 0, 1, 1, 1, 1, 1, 1, 0, 256, 256, 256, 256, 256, 64, 64, 0, kLabels11 },
    { "banker's: 80x4000 -> 4000 tall; std::round: 3616 tall", 80, 4000, 0, 1, 1, 1, 1, 1, 1, 0, 64, 4000, 64, 4000, 256, 250, 250, 0, kLabels12 },
    { "banker's: 128 wide / 80 tok; std::round: 160 wide / 100 tok", 144, 650, 0, 1, 1, 1, 1, 1, 1, 0, 128, 640, 128, 640, 256, 80, 80, 0, kLabels13 },
    { "just over one tile", 513, 513, 0, 1, 1, 1, 1, 1, 1, 0, 512, 512, 512, 512, 256, 256, 256, 0, kLabels14 },
    { "landscape 4:3 -- 3x2 grid, labelled rows=3 cols=2", 1024, 768, 1, 3, 2, 3, 2, 6, 7, 1, 1536, 1024, 576, 416, 256, 234, 1770, 6, kLabels15 },
    { "portrait 3:4 -- 2x3 grid, labelled rows=2 cols=3", 768, 1024, 1, 2, 3, 2, 3, 6, 7, 1, 1024, 1536, 416, 576, 256, 234, 1770, 6, kLabels16 },
    { "extreme panorama -- 10x1, the max_tiles ceiling", 5000, 400, 1, 10, 1, 10, 1, 10, 11, 1, 5120, 512, 1792, 128, 256, 224, 2784, 10, kLabels17 },
    { "A4 @ 300 dpi, exact ISO pixel dims", 2480, 3508, 1, 2, 3, 2, 3, 6, 7, 1, 1024, 1536, 416, 608, 256, 247, 1783, 6, kLabels18 },
    { "exactly 2x2 tiles of raw pixels", 1024, 1024, 1, 2, 2, 2, 2, 4, 5, 1, 1024, 1024, 512, 512, 256, 256, 1280, 4, kLabels19 },
};

static const int kNumCases = 20;

// _target_ratios(min_tiles=1, max_tiles=10), in the exact order upstream
// iterates it. Within one area that order comes from CPython's set
// iteration, not from the comprehension -- and it decides ties.
struct ratio_pair { int w, h; };
static const ratio_pair kTargetRatios[] = { {1, 1}, {1, 2}, {2, 1}, {3, 1}, {1, 3}, {2, 2}, {4, 1}, {1, 4}, {5, 1}, {1, 5}, {1, 6}, {6, 1}, {3, 2}, {2, 3}, {7, 1}, {1, 7}, {4, 2}, {2, 4}, {1, 8}, {8, 1}, {1, 9}, {3, 3}, {9, 1}, {2, 5}, {5, 2}, {10, 1}, {1, 10} };
static const int kNumTargetRatios = 27;

// round_by_factor(value, 32) as Python computes it (banker's rounding).
struct round_case { int value, factor, expected; };
static const round_case kRoundCases[] = {
    { 16, 32, 0 },
    { 80, 32, 64 },
    { 144, 32, 128 },
    { 208, 32, 192 },
    { 272, 32, 256 },
    { 336, 32, 320 },
    { 400, 32, 384 },
    { 464, 32, 448 },
    { 528, 32, 512 },
    { 592, 32, 576 },
    { 656, 32, 640 },
    { 720, 32, 704 },
    { 784, 32, 768 },
    { 848, 32, 832 },
    { 912, 32, 896 },
    { 976, 32, 960 },
    { 1040, 32, 1024 },
    { 1104, 32, 1088 },
    { 1168, 32, 1152 },
    { 1232, 32, 1216 },
    { 1296, 32, 1280 },
    { 1360, 32, 1344 },
    { 1424, 32, 1408 },
    { 1488, 32, 1472 },
    { 1552, 32, 1536 },
    { 1616, 32, 1600 },
    { 1680, 32, 1664 },
    { 1744, 32, 1728 },
    { 1808, 32, 1792 },
    { 1872, 32, 1856 },
    { 1936, 32, 1920 },
    { 2000, 32, 1984 },
    { 2064, 32, 2048 },
    { 2128, 32, 2112 },
    { 2192, 32, 2176 },
    { 2256, 32, 2240 },
    { 2320, 32, 2304 },
    { 2384, 32, 2368 },
    { 2448, 32, 2432 },
    { 2512, 32, 2496 },
    { 2576, 32, 2560 },
    { 2640, 32, 2624 },
    { 2704, 32, 2688 },
    { 2768, 32, 2752 },
    { 2832, 32, 2816 },
    { 2896, 32, 2880 },
    { 2960, 32, 2944 },
    { 3024, 32, 3008 },
    { 3088, 32, 3072 },
    { 3152, 32, 3136 },
    { 3216, 32, 3200 },
    { 3280, 32, 3264 },
    { 3344, 32, 3328 },
    { 3408, 32, 3392 },
    { 3472, 32, 3456 },
    { 3536, 32, 3520 },
    { 3600, 32, 3584 },
    { 3664, 32, 3648 },
    { 3728, 32, 3712 },
    { 3792, 32, 3776 },
    { 3856, 32, 3840 },
    { 3920, 32, 3904 },
    { 3984, 32, 3968 },
    { 4048, 32, 4032 },
};
static const int kNumRoundCases = sizeof(kRoundCases) / sizeof(kRoundCases[0]);

}  // namespace lfm2_tiling_golden
