#!/usr/bin/env python3
"""Regenerate tests/lfm2_posembed_golden.h from torch.

Siglip2 resizes its learned 16x16 position table with
F.interpolate(mode="bilinear", align_corners=False, antialias=True). antialias
is a no-op on upscale, so a plain bilinear matches every shape the LFM2.5-VL
tiler currently produces -- and silently does not for a patch grid below 16 in
a dimension (a 150x200 image gives 14x20). No fixture we run exercises that,
which is exactly why it needs a hermetic pin instead of a decode check.

The source table is integer-exact so the C++ rebuilds the input with no data
blob and no libm dependence.

    PYTHONPATH=<dir with torch> python tools/gen_lfm2_posembed_golden.py \
        > tests/lfm2_posembed_golden.h
"""
import numpy as np
import torch
import torch.nn.functional as F

G, D = 16, 4
CASES = [
    (32, 32, "tile grid, 2x upscale"),
    (36, 28, "thumbnail / canary grid"),
    (14, 20, "150x200 image: DOWNSCALE in h"),
    (8, 8, "2x downscale both axes"),
    (16, 16, "identity"),
    (5, 37, "mixed downscale/upscale"),
]


def main():
    y, x, c = np.meshgrid(np.arange(G), np.arange(G), np.arange(D), indexing="ij")
    src = ((y * 37 + x * 11 + c * 5) % 101).astype(np.float64) / 101.0
    t = torch.tensor(src.transpose(2, 0, 1)[None], dtype=torch.float64)

    out = []
    out.append("// GENERATED by tools/gen_lfm2_posembed_golden.py -- DO NOT EDIT BY HAND.")
    out.append("//")
    out.append('// Golden outputs of torch.nn.functional.interpolate(mode="bilinear",')
    out.append("// align_corners=False, antialias=True) -- what Siglip2 uses to resize its")
    out.append("// learned position table. The source is integer-exact so the C++ rebuilds")
    out.append("// the input with no data blob and no libm dependence.")
    out.append("#pragma once")
    out.append("namespace lfm2_posembed_golden {")
    out.append("")
    out.append(f"static const int kGrid = {G};")
    out.append(f"static const int kDim = {D};")
    out.append("")
    out.append("struct aa_case { const char * name; int out_h, out_w; const float * expect; };")
    out.append("")
    for i, (oh, ow, _) in enumerate(CASES):
        ref = F.interpolate(t, size=(oh, ow), mode="bilinear", align_corners=False,
                            antialias=True)[0].numpy().transpose(1, 2, 0).ravel()
        # %.9e always carries a decimal point and an exponent, so the `f` suffix
        # always attaches to a valid floating literal. %.9g emits a bare `0`,
        # and `0f` does not compile.
        out.append("static const float kExpect%d[] = { %s };" % (i, ", ".join(f"{v:.9e}f" for v in ref)))
    out.append("")
    out.append("static const aa_case kCases[] = {")
    for i, (oh, ow, label) in enumerate(CASES):
        out.append(f'    {{ "{label}", {oh}, {ow}, kExpect{i} }},')
    out.append("};")
    out.append(f"static const int kNumCases = {len(CASES)};")
    out.append("")
    out.append("}  // namespace lfm2_posembed_golden")
    print("\n".join(out))


if __name__ == "__main__":
    main()
